In [364]:
import numpy as np
import random

In [365]:
tur = ["Maca","Sinek","Kupa","Karo"]
kart_sayisi =range(1,14)
kart=[]

 list comprehension methodu ogren

In [366]:
for i in tur:
    for j in kart_sayisi:
        kart.append((i,j))

kart

In [367]:
random.shuffle(kart) , len(kart)

(None, 52)

In [368]:
player1=[]
player2=[]
player3=[]
player4=[]

In [369]:
def get_info(PLAYERS):
    if PLAYERS ==player1:
        print("murat")
        print(player1)
        
    elif PLAYERS ==player2:
        print("ferhat")
        print(player2)
        
    elif PLAYERS ==player3:
        print("derya")
        print(player3)
    
    elif PLAYERS ==player4:
        print("ahmet")
        print(player4)
    

In [384]:
def kart_dagit(players):
    for i in range(8):
        players.append(kart[i])
        kart.pop()
        np.random.shuffle(kart)

In [371]:
kart_dagit(player1)
kart_dagit(player2)
kart_dagit(player3)
kart_dagit(player4)

In [372]:
ortada_kalan=kart , print(type(kart))

<class 'list'>


In [382]:
def kart_degis(players,kart):
    while True:
        for _ in range(4):
            R_index=np.random.randint(0,(len(kart)-1))
            random_card=kart[R_index]
            players.append(random_card)
            kart.pop(R_index)
            kart.append(players.pop(0))
       
        a = input("Kartlardan memnun musun? (Y/N): ")
        if a.lower() != 'y':
                break

In [374]:
len(kart)

20

In [383]:
player4 

[('Karo', 4),
 ('Karo', 2),
 ('Sinek', 1),
 ('Sinek', 9),
 ('Kupa', 6),
 ('Maca', 8),
 ('Karo', 2),
 ('Kupa', 2)]

In [376]:
kart_degis(player4,kart)

In [377]:
player4

[('Karo', 4),
 ('Karo', 2),
 ('Sinek', 1),
 ('Sinek', 9),
 ('Kupa', 6),
 ('Maca', 8),
 ('Karo', 2),
 ('Kupa', 2)]

# onceki denemelerim :))

In [3]:
player1=[]
player2=[]
player3=[]
player4=[]

In [4]:
oyuncu_adeti=4
kac_kart=8

In [10]:
kart =np.array([maca,sinek,kupa,karo])

In [11]:
kart

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

In [21]:
kart[3][2], kart[0][12] , print("----") ,

----


(2, 12, None, 2)

In [27]:
kart.shape , kart.ndim

((4, 14), 2)

In [22]:
for i in kart:
    np.random.shuffle(i)

In [28]:
kart

array([[13,  8, 10, 12,  2,  9,  7, 11,  6,  1,  3,  5,  4,  0],
       [11,  9,  8,  1,  0,  2,  7,  4, 12,  5,  3, 10,  6, 13],
       [ 9,  7,  3,  8, 10,  1,  5,  4, 11,  0,  6, 13, 12,  2],
       [ 0, 12,  8,  3,  9,  4,  6, 11,  5, 10, 13,  7,  2,  1]])

In [36]:
stack = kart.flatten()

In [37]:
stack

array([13,  8, 10, 12,  2,  9,  7, 11,  6,  1,  3,  5,  4,  0, 11,  9,  8,
        1,  0,  2,  7,  4, 12,  5,  3, 10,  6, 13,  9,  7,  3,  8, 10,  1,
        5,  4, 11,  0,  6, 13, 12,  2,  0, 12,  8,  3,  9,  4,  6, 11,  5,
       10, 13,  7,  2,  1])

In [116]:
def kart_dagit(x):
   
    for i in range(kac_kart):
        a=random.randint(0,3)
        b=random.randint(0,13)
        print(kart[a][b])
            
    
    

In [31]:
maca = np.arange(1,15)
sinek= np.arange(1,15)
kupa= np.arange(1,15)
karo= np.arange(1,15)
stack=np.arange(1,53)

In [38]:
suits = ['Maca', 'Sinek', 'Kupa', 'Karo']
values = np.arange(1, 14)

In [39]:
deck = [(suit, value) for suit in suits for value in values]
np.random.shuffle(deck)

In [42]:
print("player1'in Kartları:")
for suit, value in player1_cards:
    print(f"{suit} {value}")


player1'in Kartları:
Karo 4
Karo 13
Karo 10
Karo 8
Sinek 11
Maca 6
Maca 3
Kupa 1


In [104]:
kart[2][12]

5

In [40]:
player1_cards = [deck.pop() for _ in range(8)]


In [117]:
kart_dagit(player1)

6
9
10
8
13
1
2
0
